site:
  title: Pwning OWASP Juice Shop
  url: https://juice-shop.herokuapp.com
content:
  sources:
  - url: .
    start_path: docs
    branches: antora-migration, antora-develop
  - url: https://github.com/asciidoctor/asciidoctor.js
    branches: 3.0.x, v2.2.x
    start_path: docs
ui:
  bundle:
    url: /Users/parthnanda/Desktop/Gsoc/JuiceShop-UI-antora/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./build

antora:
  extensions:
  - '@antora/lunr-extension'