site:
  title: Pwning OWASP Juice Shop
content:
  sources:
  - url: 
    start_path: ./
    branches: [antora-migration, 1.1]


ui:
  bundle:
    url: /Users/parthnanda/Desktop/Gsoc/JuiceShop-UI-antora/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./docs

antora:
  extensions:
  - '@antora/lunr-extension'