name: "ZAP Baseline Scan"

on:
  schedule:
    - cron:  '0 19 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: 'Scan "Pwning OWASP Juice Shop" Antora instance'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://pwning.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
